#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf 0
rm -rf AlphaInit
rm -rf constant/*/polyMesh
rm boilingPost*
rm fluid* solid* heater*
cp system/controlDict.sp system/controlDict; cp system/heater/fvOptions.sp system/heater/fvOptions; cp system/fluid/fvSolution.sp system/fluid/fvSolution
#------------------------------------------------------------------------------
