#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication blockMesh
runApplication snappyHexMesh -overwrite 
runApplication topoSet
rm -r 0
cp -r 0.orig 0
runApplication splitMeshRegions -cellZones -overwrite
rm -rf constant/polyMesh

#runApplication decomposePar -allRegions
#runParallel $(getApplication)
#runApplication reconstructPar -allRegions


#------------------------------------------------------------------------------
