#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# generate mesh
runApplication blockMesh
runApplication topoSet
mv log.topoSet log.topoSet.init
cp -r orig.0 0
runApplication splitMeshRegions -cellZones -overwrite
rm -r constant/polyMesh

# generate bubble
runApplication setFields -region fluid
runApplication setAlphaFieldDyn -region fluid
cp -rf 5e-10/fluid/* 0/fluid/
rm -rf *e-10
runApplication icoBoilingFoam


#------------------------------------------------------------------------------
