#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf 0 constant system
rm -rf AlphaInit
rm boilingPost*
rm fluid* solid* heater*
rm simSetup
#------------------------------------------------------------------------------
