#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r ../singlePhase/constant .
cp -r ../singlePhase/0.* .
mv 0.* 0
#cp -r ../singlePhase/dynamicCode .
rm 0/uniform/time
runApplication setFields -region fluid

#------------------------------------------------------------------------------
