#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# generate mesh
runApplication blockMesh
runApplication topoSet
mv log.topoSet log.topoSet.init
#restore0Dir
rm -r 0
cp -r orig.0 0
runApplication splitMeshRegions -cellZones -overwrite
#runApplication changeDictionary
#mv log.changeDictionary log.changeDictionary.init
rm -r constant/polyMesh



#------------------------------------------------------------------------------
