#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r ../singlePhase/0.* .; cp -r ../singlePhase/constant .; cp -r ../singlePhase/system .
mv 0.* 0; rm 0/uniform/time; mv system/controlDict.tp system/controlDict; mv system/fluid/fvSchemes.tp system/fluid/fvSchemes; mv system/fluid/fvSolution.tp system/fluid/fvSolution

runApplication setFields -region fluid

#runApplication decomposePar -region fluid

# run solver
#runParallel $(getApplication)

#------------------------------------------------------------------------------
