#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh -region fluid
cp -r orig.0 0

#runApplication decomposePar -region fluid
#runParallel $(getApplication)

#------------------------------------------------------------------------------
