#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf 0
rm -r AlphaInit/
rm -rf constant/*/polyMesh
rm -rf processor*
rm bubbleInfo.csv

#------------------------------------------------------------------------------
